name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t logger .

      - name: Run Docker container
        run: docker run --rm -v "${{ github.workspace }}/logs/:/home/logs/" logger

      - name: Prepare logs directory
        run: |
          rm -rf logs
          mkdir logs
          echo "No logs generated, creating dummy.log" > logs/dummy.log

      - name: Check logs directory
        run: ls -R logs/

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
